# Unrelated
""" input_texts = [
    "Gardening is more than just a pastime; it’s a nurturing process that connects us with nature and sparks creativity. Each seed planted represents a small act of hope, carrying the promise of vibrant blossoms or fresh vegetables. Tending to soil, watering regularly, and removing weeds teaches patience and dedication. The rewards are manifold: from the soothing effect of working outdoors to the satisfaction of watching tiny sprouts grow into healthy plants. Gardening also reduces stress and encourages mindfulness. It’s not merely about tending flowers but also fostering one’s sense of purpose, making it a truly enriching and satisfying hobby.",

    "Modern architecture pushes the boundaries of design through innovative materials and cutting-edge construction methods. Sleek lines, open layouts, and sustainable features are hallmarks of these contemporary structures. Steel, glass, and concrete often dominate the aesthetic, giving rise to buildings that seamlessly merge function with striking form. From towering skyscrapers in bustling cities to eco-friendly homes nestled in quiet suburbs, modern architecture reflects the ever-evolving needs of our society. Advanced technologies like 3D printing and virtual reality also shape the field, allowing architects to experiment with bold ideas. Ultimately, modern architecture redefines how we experience and inhabit the spaces we call home.",

    "Classical literature stands as a timeless testament to human creativity, illuminating universal truths across centuries. Works by authors like Homer, Shakespeare, and Tolstoy transport readers into distant realms and eras while grappling with themes such as love, power, and morality. These texts challenge us to question our assumptions, confront human frailties, and celebrate resilience. Often written in elevated language and complex structures, they encourage deep reading and reflection. Though centuries may separate modern audiences from these authors, their words resonate with emotional honesty and vibrant storytelling. Classical literature thus endures as a cornerstone of education, culture, and profound intellectual engagement.",

    "Wildlife conservation is crucial for maintaining the balance of ecosystems worldwide. Every species, from the smallest insects to majestic whales, plays a unique role in the intricate web of life. When one species diminishes or disappears, it affects countless others, disrupting food chains and natural processes. Conservation efforts focus on habitat protection, anti-poaching regulations, and education initiatives that highlight the importance of biodiversity. Protecting endangered species not only preserves natural heritage but also ensures resources like clean water and fertile soil for future generations. Through collective action and responsible stewardship, we can safeguard our planet’s incredible array of life forms.",

    "Ancient mythology offers rich narratives that reveal the values, fears, and aspirations of early civilizations. Myths about gods, heroes, and creatures were deeply intertwined with daily life, often explaining natural phenomena or teaching moral lessons. Greek tales of Zeus and Athena, Norse sagas of Thor and Odin, and Egyptian stories of Ra and Anubis continue to captivate modern audiences. These stories served as both religious texts and cultural touchstones, shaping everything from political power structures to artistic expression. Despite their fantastical elements, myths hold enduring relevance, emphasizing universal themes such as love, betrayal, and the relentless pursuit of knowledge.",

    "Digital art has revolutionized the creative landscape by merging traditional artistic expression with modern technology. Artists can now sketch, paint, and sculpt in virtual environments using advanced software and tools. This flexibility opens up endless possibilities for experimentation, as layers can be added or removed, and color palettes adjusted instantly. Social media platforms provide opportunities for digital artists to share their work globally, garnering feedback and inspiration from diverse audiences. Moreover, new mediums like NFTs have emerged, offering novel ways to buy and sell digital pieces. As technology evolves, digital art continues to expand, reshaping our understanding of creativity.",

    "Personal finance revolves around budgeting, saving, and investing wisely to secure one’s financial well-being. Planning starts with a clear overview of monthly income and expenses, which helps identify unnecessary costs and prioritize essential spending. Building an emergency fund is vital to handle unexpected events like medical bills or car repairs without accruing debt. Investing strategies can vary—some prefer stocks, while others lean toward real estate or mutual funds. It’s also important to manage credit responsibly, aiming to maintain a strong credit score. Good personal finance habits cultivate stability and peace of mind, helping people reach both short-term and long-term goals.",

    "World cuisine is a vibrant tapestry of flavors, reflecting the history, geography, and cultural traditions of diverse regions. From the aromatic spices of Indian curries to the comforting pasta dishes of Italian homes, each culinary style tells a story of local ingredients and techniques passed down through generations. Street food in Southeast Asia, for example, combines sweet, salty, and spicy elements in bold combinations that awaken the palate. Regional specialties often highlight fresh, seasonal produce, celebrating the bounty of land and sea. As cultures interact and globalize, fusion dishes emerge, blending time-honored recipes with modern twists to create mouthwatering new experiences.",
] """

# Some related
""" input_texts = [
    "On a quiet afternoon in a charming town, sunlight filters through ancient trees lining a peaceful boulevard. Neighbors chat while strolling along cobblestone streets, their voices mingling with the soft rustle of leaves in a gentle breeze. Small cafés serve freshly brewed coffee and homemade pastries, adding a welcoming aroma to the air. Children laugh in nearby parks as local artisans display handcrafted goods on quaint sidewalks. Every detail, from the historic architecture to the friendly smiles, creates an atmosphere of warmth and community, inviting everyone to pause and savor the simple, everyday beauty of life.",
    
    "In a serene coastal village, the calming sound of ocean waves sets a tranquil rhythm for daily life. Sun-drenched streets wind past weathered cottages adorned with vibrant blooms and inviting doorways. Locals greet one another with warm smiles, while seaside cafés serve aromatic teas and fresh, locally sourced treats. Children play near the gentle shoreline as fishermen prepare for the day, their boats bobbing in the harbor. The harmonious blend of salty air, soft sea breezes, and timeless traditions creates an ambiance of peaceful coexistence, encouraging residents and visitors alike to embrace the charm of a relaxed, seaside existence.",
    
    "World cuisine is a vibrant tapestry of flavors, reflecting the history, geography, and cultural traditions of diverse regions. From the aromatic spices of Indian curries to the comforting pasta dishes of Italian homes, each culinary style tells a story of local ingredients and techniques passed down through generations. Street food in Southeast Asia, for example, combines sweet, salty, and spicy elements in bold combinations that awaken the palate. Regional specialties often highlight fresh, seasonal produce, celebrating the bounty of land and sea. As cultures interact and globalize, fusion dishes emerge, blending time-honored recipes with modern twists to create mouthwatering new experiences.",
    
    "World cuisine is a vibrant tapestry of flavors, reflecting the history, geography, and cultural traditions of diverse regions. From the aromatic spices of Indian curries to the comforting pasta dishes of Italian homes, each culinary style tells a story of local ingredients and techniques passed down through generations. Street food in Southeast Asia, for example, combines sweet, salty, and spicy elements in bold combinations that awaken the palate. Regional specialties often highlight fresh, seasonal produce, celebrating the bounty of land and sea. As cultures interact and globalize, fusion dishes emerge, blending time-honored recipes with modern twists to create mouthwatering new experiences.",
    
    "World cuisine is a vibrant tapestry of flavors, reflecting the history, geography, and cultural traditions of diverse regions. From the aromatic spices of Indian curries to the comforting pasta dishes of Italian homes, each culinary style tells a story of local ingredients and techniques passed down through generations. Street food in Southeast Asia, for example, combines sweet, salty, and spicy elements in bold combinations that awaken the palate. Regional specialties often highlight fresh, seasonal produce, celebrating the bounty of land and sea. As cultures interact and globalize, fusion dishes emerge, blending time-honored recipes with modern twists to create mouthwatering new experiences.",
    
    "Ancient mythology offers rich narratives that reveal the values, fears, and aspirations of early civilizations. Myths about gods, heroes, and creatures were deeply intertwined with daily life, often explaining natural phenomena or teaching moral lessons. Greek tales of Zeus and Athena, Norse sagas of Thor and Odin, and Egyptian stories of Ra and Anubis continue to captivate modern audiences. These stories served as both religious texts and cultural touchstones, shaping everything from political power structures to artistic expression. Despite their fantastical elements, myths hold enduring relevance, emphasizing universal themes such as love, betrayal, and the relentless pursuit of knowledge.",
    
    "Ancient mythology offers rich narratives that reveal the values, fears, and aspirations of early civilizations. Myths about gods, heroes, and creatures were deeply intertwined with daily life, often explaining natural phenomena or teaching moral lessons. Greek tales of Zeus and Athena, Norse sagas of Thor and Odin, and Egyptian stories of Ra and Anubis continue to captivate modern audiences. These stories served as both religious texts and cultural touchstones, shaping everything from political power structures to artistic expression. Despite their fantastical elements, myths hold enduring relevance, emphasizing universal themes such as love, betrayal, and the relentless pursuit of knowledge.",
    
    "Ancient mythology offers rich narratives that reveal the values, fears, and aspirations of early civilizations. Myths about gods, heroes, and creatures were deeply intertwined with daily life, often explaining natural phenomena or teaching moral lessons. Greek tales of Zeus and Athena, Norse sagas of Thor and Odin, and Egyptian stories of Ra and Anubis continue to captivate modern audiences. These stories served as both religious texts and cultural touchstones, shaping everything from political power structures to artistic expression. Despite their fantastical elements, myths hold enduring relevance, emphasizing universal themes such as love, betrayal, and the relentless pursuit of knowledge.",
] """

# Different languages

input_texts = [
    "Gardening is more than just a pastime; it’s a nurturing process that connects us with nature and sparks creativity. Each seed planted represents a small act of hope, carrying the promise of vibrant blossoms or fresh vegetables. Tending to soil, watering regularly, and removing weeds teaches patience and dedication. The rewards are manifold: from the soothing effect of working outdoors to the satisfaction of watching tiny sprouts grow into healthy plants. Gardening also reduces stress and encourages mindfulness. It’s not merely about tending flowers but also fostering one’s sense of purpose, making it a truly enriching and satisfying hobby.",

    "Η κηπουρική είναι κάτι περισσότερο από ένα χόμπι. είναι μια διαδικασία φροντίδας που μας συνδέει με τη φύση και πυροδοτεί τη δημιουργικότητα. Κάθε σπόρος που φυτεύεται αντιπροσωπεύει μια μικρή πράξη ελπίδας, που φέρει την υπόσχεση για ζωντανά άνθη ή φρέσκα λαχανικά. Η φροντίδα του εδάφους, το τακτικό πότισμα και η αφαίρεση των ζιζανίων διδάσκει υπομονή και αφοσίωση. Οι ανταμοιβές είναι πολλαπλές: από το καταπραϋντικό αποτέλεσμα της εργασίας σε εξωτερικούς χώρους μέχρι την ικανοποίηση να παρακολουθείς μικροσκοπικά βλαστάρια να μεγαλώνουν σε υγιή φυτά. Η κηπουρική μειώνει επίσης το άγχος και ενθαρρύνει την επίγνωση. Δεν αφορά απλώς την περιποίηση λουλουδιών, αλλά και την ενίσχυση της αίσθησης του σκοπού, καθιστώντας το ένα πραγματικά εμπλουτιστικό και ικανοποιητικό χόμπι.",

    "Tuinieren is meer dan alleen een tijdverdrijf; het is een verzorgend proces dat ons verbindt met de natuur en creativiteit aanwakkert. Elk geplant zaadje vertegenwoordigt een kleine daad van hoop, met de belofte van levendige bloesems of verse groenten. Het verzorgen van de grond, regelmatig water geven en onkruid verwijderen leert geduld en toewijding. De beloningen zijn veelvoudig: van het rustgevende effect van buiten werken tot de voldoening van het zien uitgroeien van kleine spruitjes tot gezonde planten. Tuinieren vermindert ook stress en stimuleert mindfulness. Het gaat niet alleen om het verzorgen van bloemen, maar ook om het bevorderen van iemands gevoel van doelgerichtheid, waardoor het een werkelijk verrijkende en bevredigende hobby is.",

    "Il giardinaggio è più di un semplice passatempo; è un processo di cura che ci collega alla natura e stimola la creatività. Ogni seme piantato rappresenta un piccolo atto di speranza, che porta con sé la promessa di fiori vivaci o verdure fresche. Prendersi cura del terreno, annaffiare regolarmente e rimuovere le erbacce insegna pazienza e dedizione. Le ricompense sono molteplici: dall'effetto lenitivo del lavoro all'aperto alla soddisfazione di vedere piccoli germogli crescere e diventare piante sane. Il giardinaggio riduce anche lo stress e incoraggia la consapevolezza. Non si tratta solo di prendersi cura dei fiori, ma anche di promuovere il proprio senso di scopo, rendendolo un hobby davvero arricchente e soddisfacente.",

    "Ogrodnictwo to coś więcej niż tylko hobby; to proces pielęgnowania, który łączy nas z naturą i pobudza kreatywność. Każde zasadzone nasionko to mały akt nadziei, niosący obietnicę bujnych kwiatów lub świeżych warzyw. Dbanie o glebę, regularne podlewanie i usuwanie chwastów uczy cierpliwości i poświęcenia. Nagrody są liczne: od kojącego efektu pracy na świeżym powietrzu po satysfakcję z obserwowania, jak maleńkie kiełki wyrastają na zdrowe rośliny. Ogrodnictwo zmniejsza również stres i zachęca do uważności. Nie chodzi tu tylko o pielęgnację kwiatów, ale także o pielęgnowanie poczucia celu, co czyni je naprawdę wzbogacającym i satysfakcjonującym hobby.",
]

""" input_texts = [
    "Ancient mythology offers rich narratives that reveal the values, fears, and aspirations of early civilizations. Myths about gods, heroes, and creatures were deeply intertwined with daily life, often explaining natural phenomena or teaching moral lessons. Greek tales of Zeus and Athena, Norse sagas of Thor and Odin, and Egyptian stories of Ra and Anubis continue to captivate modern audiences. These stories served as both religious texts and cultural touchstones, shaping everything from political power structures to artistic expression. Despite their fantastical elements, myths hold enduring relevance, emphasizing universal themes such as love, betrayal, and the relentless pursuit of knowledge.",    
    "Ancient mythology offers rich narratives that reveal the values, fears, and aspirations of early civilizations. Myths about gods, heroes, and creatures were deeply intertwined with daily life, often explaining natural phenomena or teaching moral lessons. Greek tales of Zeus and Athena, Norse sagas of Thor and Odin, and Egyptian stories of Ra and Anubis continue to captivate modern audiences. These stories served as both religious texts and cultural touchstones, shaping everything from political power structures to artistic expression. Despite their fantastical elements, myths hold enduring relevance, emphasizing universal themes such as love, betrayal, and the relentless pursuit of knowledge.",
    "Ancient mythology offers rich narratives that reveal the values, fears, and aspirations of early civilizations. Myths about gods, heroes, and creatures were deeply intertwined with daily life, often explaining natural phenomena or teaching moral lessons. Greek tales of Zeus and Athena, Norse sagas of Thor and Odin, and Egyptian stories of Ra and Anubis continue to captivate modern audiences. These stories served as both religious texts and cultural touchstones, shaping everything from political power structures to artistic expression. Despite their fantastical elements, myths hold enduring relevance, emphasizing universal themes such as love, betrayal, and the relentless pursuit of knowledge.",
    "Ancient mythology offers rich narratives that reveal the values, fears, and aspirations of early civilizations. Myths about gods, heroes, and creatures were deeply intertwined with daily life, often explaining natural phenomena or teaching moral lessons. Greek tales of Zeus and Athena, Norse sagas of Thor and Odin, and Egyptian stories of Ra and Anubis continue to captivate modern audiences. These stories served as both religious texts and cultural touchstones, shaping everything from political power structures to artistic expression. Despite their fantastical elements, myths hold enduring relevance, emphasizing universal themes such as love, betrayal, and the relentless pursuit of knowledge.",    
    "Ancient mythology offers rich narratives that reveal the values, fears, and aspirations of early civilizations. Myths about gods, heroes, and creatures were deeply intertwined with daily life, often explaining natural phenomena or teaching moral lessons. Greek tales of Zeus and Athena, Norse sagas of Thor and Odin, and Egyptian stories of Ra and Anubis continue to captivate modern audiences. These stories served as both religious texts and cultural touchstones, shaping everything from political power structures to artistic expression. Despite their fantastical elements, myths hold enduring relevance, emphasizing universal themes such as love, betrayal, and the relentless pursuit of knowledge.",
    "Ancient mythology offers rich narratives that reveal the values, fears, and aspirations of early civilizations. Myths about gods, heroes, and creatures were deeply intertwined with daily life, often explaining natural phenomena or teaching moral lessons. Greek tales of Zeus and Athena, Norse sagas of Thor and Odin, and Egyptian stories of Ra and Anubis continue to captivate modern audiences. These stories served as both religious texts and cultural touchstones, shaping everything from political power structures to artistic expression. Despite their fantastical elements, myths hold enduring relevance, emphasizing universal themes such as love, betrayal, and the relentless pursuit of knowledge.",
    "Ancient mythology offers rich narratives that reveal the values, fears, and aspirations of early civilizations. Myths about gods, heroes, and creatures were deeply intertwined with daily life, often explaining natural phenomena or teaching moral lessons. Greek tales of Zeus and Athena, Norse sagas of Thor and Odin, and Egyptian stories of Ra and Anubis continue to captivate modern audiences. These stories served as both religious texts and cultural touchstones, shaping everything from political power structures to artistic expression. Despite their fantastical elements, myths hold enduring relevance, emphasizing universal themes such as love, betrayal, and the relentless pursuit of knowledge.",    
    "Ancient mythology offers rich narratives that reveal the values, fears, and aspirations of early civilizations. Myths about gods, heroes, and creatures were deeply intertwined with daily life, often explaining natural phenomena or teaching moral lessons. Greek tales of Zeus and Athena, Norse sagas of Thor and Odin, and Egyptian stories of Ra and Anubis continue to captivate modern audiences. These stories served as both religious texts and cultural touchstones, shaping everything from political power structures to artistic expression. Despite their fantastical elements, myths hold enduring relevance, emphasizing universal themes such as love, betrayal, and the relentless pursuit of knowledge.",
] """
  
""" countries = [
    "India", "Barbados", "Canada", "Hungary" ,"Lithuania", "Andorra", "Brazil", "Bulgaria", "France", "Ukraine"
]
input_texts = [
    "In the village of Eldara, spirited Meera discovers a cursed temple and encounters the ghostly Lila, who reveals a betrayal that severed the villagers’ bond with nature. To lift the curse, Meera rallies her skeptical community to restore harmony with the forest, transforming Eldara into a thriving, interconnected haven.",
    "In The Echoes of Emerald Isle, travel writer Claire Mendez visits Barbados seeking rejuvenation after personal struggles. Immersed in the island's rich culture and history, she bonds with locals, particularly fisherman Jamal. Through exploration and storytelling, Claire discovers resilience and belonging, transforming her journey into a profound self-discovery before returning home.",
    "In a picturesque Ontario town, artist Emma Thompson returns home seeking inspiration. Invited to showcase her work, she reconnects with childhood friend Sarah and discovers new love with Jake, a photographer. Amidst a winter storm, their bond deepens, heralding the start of a new season filled with creativity and romance.",
    "In 2023, young historian Anna Gulyás arrives in Pécs, Hungary, seeking the truth behind the legend of the Whispering Pines. As she connects with the trees' ancient wisdom, she uncovers dark tales of betrayal. Organizing a gathering, she confronts the spirit of a ruthless nobleman, emphasizing the importance of honoring history.",
    "In Lithuania's enchanted Whispering Woods, young Eglė, a curious girl, heeds the call of nature's spirit to restore balance threatened by darkness. Guided by ancient whispers, she embarks on a quest to find the Source of Light within the forest. Through courage and hope, she triumphs, becoming the village's Guardian.",
    "In the enchanting valleys of Andorra, young Clara receives an invitation to a royal festival. There, she meets the charming prince, and their unexpected connection leads to secret adventures exploring their homeland. As their bond deepens, Clara grapples with societal expectations, ultimately discovering a love that transcends titles and traditions.",
    "In the vibrant town of São Miguel, Maria Clara prepares to lead the 50th Carnival in honor of her late grandmother, Abuela Rosa. As she dances, she forms a deep connection with a mysterious man named Lucas. Together, they celebrate love, heritage, and new beginnings, embodying the festival’s enduring spirit.",
    "In the Bulgarian village of Pirot, young Mira embarks on an adventurous journey to the Rila Mountains, where she encounters Lira, a guardian spirit. Inspired to protect the land, Mira rallies her community to embrace their connection to nature. Together, they cultivate a deeper bond with their environment, ensuring the mountains’ enduring spirit.",
    "In the charming village of Vergeroux, friends Amélie and Julien embark on an adventure into the mystical Forest of Emerald, rumored to hide a treasure that grants wishes. Guided by a fairy, they learn that true wealth lies in wisdom and friendship. They wish for their village's prosperity, discovering the power of love and hard work.",
    "In a picturesque Ukrainian village by the Dnipro River, young Kateryna’s adventurous spirit awakens amidst whispers of political unrest. As protests rise, she rallies her friends to fight for freedom, transforming from a curious girl into a courageous leader. Through unity and resilience, they forge a hopeful path for their future.",
] """



def text_grouping(tokenizer: any, paragraphs: list):
    """
    
    return: input_texts_token_lengths
    """
    input_texts_token_lengths = [
        len(tokenizer.encode(paragraph))
        for paragraph in paragraphs
    ]
    
    """ print("Token lengths per paragraph:", input_texts_token_lengths)
    print("Cumulative sums:", np.cumsum(input_texts_token_lengths))
    print("Nr texts: ", len(input_texts)) """
    return input_texts_token_lengths
